apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-1
  namespace: demo-1
  labels:
    app: demo-1
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: demo-1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
      labels:
        app: demo-1
    spec:
      containers:
      - name: demo-1
        image: registry.cn-hangzhou.aliyuncs.com/acs/rollouts-demo-1:red
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: demo-1-svc
  namespace: demo-1
spec:
  selector:
    app: demo-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-1
  namespace: demo-1
  labels:
    app: demo-1
spec:
  rules:
    - host: app.demo-1.example.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: demo-1-svc
              port:
                number: 80