apiVersion: core.oam.dev/v1alpha1
kind: Workflow
metadata:
  name: deploy-demo
steps:
  - type: deploy
    name: deploy-test
    properties:
      policies: ["cluster-test"]
  - type: deploy
    name: deploy-prod
    properties:
      auto: false
      policies: ["cluster-prod"]